name: "Increment the version code/name/stage of your Android project"
description: "This action will increment the version code/name/stage directly in build.gradle . "
inputs:
  gradlePath:
    description: "Gradle path to override version"
    required: true
    default: "app/build.gradle"
  versionCode:
    description: "The new version code"
    required: false
  versionCodeLimiter:
    description: "Limit to the last digest when adding to the version name"
    required: false
  versionName:
    description: "The new version name"
    required: false
  versionStage:
    description: "The stage of the app"
    required: false
outputs:
  result: # id of output
    description: "Action Result"
runs:
  using: "node12"
  main: "index.js"
branding:
  color: 'blue'
  icon: 'anchor'
